# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "crates/database_schema/src/lib.rs"
custom_type_derives = ["diesel::query_builder::QueryId"]

[migrations_directory]
dir = "crates/database/migrations"
