x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "50m"
    max-file: "4"

services:

  ibis:
    image: nutomic/ibis:{version}
    ports:
      - "127.0.0.1:3000:3000"
    restart: always
    logging: *default-logging
    environment:
      - LEPTOS_SITE_ADDR=0.0.0.0:3000
    volumes:
      - ./config.toml:/config.toml:Z
    depends_on:
      - postgres

  postgres:
    image: docker.io/pgautoupgrade/pgautoupgrade:16-alpine
    restart: always
    environment:
      - POSTGRES_USER=ibis
      - POSTGRES_PASSWORD={your-db-password}
      - POSTGRES_DB=ibis
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data:Z
    logging: *default-logging

  postfix:
    image: docker.io/mwader/postfix-relay
    restart: always
    logging: *default-logging