# Details about the PostgreSQL database connection
[database]
# Database connection url
connection_url = "postgres://ibis:password@localhost:5432/ibis"

# Database connection pool size
pool_size = 5

# Details of the initial admin account
[setup]
admin_username = "ibis"
admin_password = "ibis"

[federation]
# Domain name of the instance, mandatory for federation
domain = "example.com"

# Comma separated list of instances which are allowed for federation. If set, federation
# with other domains is blocked
# Optional
allowlist = "good.com,friends.org"

# Comma separated list of instances which are blocked for federation; optional
blocklist = "evil.com,bad.org"

[options]
# Whether users can create new accounts
registration_open = true

# Whether admins need to approve new articles
article_approval = false
